export const GET_JEWELRY_REQUEST = "GET_JEWELRY_REQUEST";
export const GET_JEWELRY_SUCCESS = "GET_JEWELRY_SUCCESS";
export const GET_JEWELRY_FAILURE = "GET_JEWELRY_FAILURE";

export const SORT_LOW_TO_HIGH = "SORT_LOW_TO_HIGH";
export const SORT_HIGH_TO_LOW = "SORT_HIGH_TO_LOW";

export const NAME_A_TO_Z = "NAME_A_TO_Z";
export const NAME_Z_TO_A = "NAME_Z_TO_A";
