export const GET_JEWELRY_REQUEST = "GET_JEWELRY_REQUEST";
export const GET_JEWELRY_SUCCESS = "GET_JEWELRY_SUCCESS";
export const GET_JEWELRY_FAILURE = "GET_JEWELRY_FAILURE";

export const SORT_PRICE_HTL = "SORT_PRICE_HTL";
export const SORT_PRICE_LTH = "SORT_PRICE_LTH";

export const SORT_ALPHABETICALLY_A_Z = "SORT_ALPHABETICALLY_A_Z";
export const SORT_ALPHABETICALLY_Z_A = "SORT_ALPHABETICALLY_Z_A";

export const SORT_DATE_OLD_TO_NEW = "SORT_DATE_OLD_TO_NEW";
export const SORT_DATE_NEW_TO_OLD = "SORT_DATE_NEW_TO_OLD";

export const BEST_SELLING = "BEST_SELLING";
export const FEATURED = "FEATURED";
